framework:
    default_locale: pl
    translator:
        paths: [ '%kernel.project_dir%/translations' ]
        fallbacks: ['en', 'pl']
        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#                domains: [ 'messages' ]
#                locales: [ 'en', 'pl' ]
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
